name: flutter_application_2
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_linkify: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_olm: ^2.0.0
  flutter_openssl_crypto: ^0.5.0
  matrix: ^0.35.0
  path_provider: ^2.1.5
  provider: ^6.1.2
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
